
/** required package class namespace */
package testing.sampleIA.simpleversion;

/** required imports */
import collections.LinkedList;
import io.FileHandler;
import javax.swing.JOptionPane;
import tools.Search;
import tools.Sort;


/**
 * UserInterface.java - a simple example of a I.B. I.A. It uses the speed and
 * convenience of the NetBeans visual editor to build a user interface and 
 * uses the associated classes LinkedList, Search, Sort, and FileHandler that
 * we developed in class when learning those concepts. 
 *
 * @author Mr. Wachs
 * @since Mar. 6, 2020, 2:04:34 p.m.
 */
public class UserInterface extends javax.swing.JFrame 
{

    // classes for specific tasks, imported from our own packages 
    private LinkedList<String>              names  = new LinkedList<>();
    private Search                          search = new Search();
    private Sort                            sort   = new Sort();
    private FileHandler<LinkedList<String>> file   = new FileHandler<>();
    
    // constant for the file name to save to
    private final String FILENAME = "data.txt";
    
    /** 
     * Default constructor, creates new form UserInterface 
     */
    public UserInterface() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnterName = new javax.swing.JButton();
        lstNames = new java.awt.List();
        btnSearchNames = new javax.swing.JButton();
        btnSortNames = new javax.swing.JButton();
        btnSaveNames = new javax.swing.JButton();
        btnOpenNames = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Database");
        setResizable(false);

        btnEnterName.setText("Enter Name");
        btnEnterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterNameActionPerformed(evt);
            }
        });

        btnSearchNames.setText("Search Names");
        btnSearchNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNamesActionPerformed(evt);
            }
        });

        btnSortNames.setText("Sort Names");
        btnSortNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortNamesActionPerformed(evt);
            }
        });

        btnSaveNames.setText("Save Names");
        btnSaveNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNamesActionPerformed(evt);
            }
        });

        btnOpenNames.setText("Open Names");
        btnOpenNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenNamesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSearchNames, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(lstNames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEnterName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnSortNames, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(btnSaveNames, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(btnOpenNames, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEnterName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstNames, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchNames, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSortNames, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveNames, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOpenNames, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterNameActionPerformed
        String name = JOptionPane.showInputDialog("Enter name to add");
        names.add(name);
        lstNames.add(name);
    }//GEN-LAST:event_btnEnterNameActionPerformed

    private void btnSearchNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNamesActionPerformed
        String name = JOptionPane.showInputDialog("Enter name to search for");
        int index = search.linear(name, names);
        lstNames.select(index);
    }//GEN-LAST:event_btnSearchNamesActionPerformed

    private void btnSortNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortNamesActionPerformed
        sort.bubble(names);
        showList();
    }//GEN-LAST:event_btnSortNamesActionPerformed

    private void btnSaveNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNamesActionPerformed
        file.saveObject(names, FILENAME);
    }//GEN-LAST:event_btnSaveNamesActionPerformed

    private void btnOpenNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenNamesActionPerformed
        names = (LinkedList<String>)file.openObject(FILENAME);
        showList();
    }//GEN-LAST:event_btnOpenNamesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnterName;
    private javax.swing.JButton btnOpenNames;
    private javax.swing.JButton btnSaveNames;
    private javax.swing.JButton btnSearchNames;
    private javax.swing.JButton btnSortNames;
    private java.awt.List lstNames;
    // End of variables declaration//GEN-END:variables

    private void showList() {
        lstNames.removeAll();
        for (int i = 0; i < names.size(); i++) {
            lstNames.add(names.get(i));
        }
    }
    
}
