
/** required package class namespace */
package testing.testclass;

/** required imports */
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 * TestClassUI.java - test class user interface model
 * 
 * @author Mr. Wachs
 * @since Dec 12, 2016
 * @instructor Mr. Wachs
 */
public class TestClassUI extends javax.swing.JDialog {

    private TestClassUIController engine;
    
    /**
     * Class constructor sets class property data
     * 
     * @param parent the parent object to parent this user interface to
     * @param modal should the user interface be in model form (true) or not (false)
     */
    public TestClassUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        JLabel[] textLabels = {
            jLabel3,jLabel2,jLabel4,jLabel5,jLabel6,
            jLabel7,jLabel8,jLabel1,jLabel9,jLabel10            
        };   
        JTextField[]  textboxes = {
            jTextField2,jTextField3,jTextField4,
            jTextField5,jTextField6
        };
        JComboBox[] comboboxes = {
            jComboBox1,jComboBox2,jComboBox3,jComboBox4,jComboBox5
        };
        JButton[] buttons = {
          jButton1,jButton2,jButton3,jButton4,jButton5,
          jButton6,jButton7,jButton8,jButton9,jButton10
        };
        JList listbox = jList1;
        engine = new TestClassUIController(jPanel1,textLabels,
                textboxes,comboboxes,buttons,listbox,this);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Generated Object", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 11))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jLabel1.setText("SuperClass Array 3 (double) : ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 240, 200, 20);

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jLabel2.setText("TestClass Data 2 (Integer) : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 60, 200, 20);

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jLabel3.setText("TestClass Data 1 (Boolean) : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 30, 200, 20);

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jLabel4.setText("TestClass Data 3 (Double) : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 90, 200, 20);

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jLabel5.setText("TestClass Data 4 (Character) : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 120, 200, 20);

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jLabel6.setText("AssociateClass Data 5 (String) : ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 150, 200, 20);

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jLabel7.setText("SuperClass Array 1 (bool) : ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 180, 200, 20);

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jLabel8.setText("SuperClass Array 2 (int) : ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 210, 200, 20);

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jLabel9.setText("SuperClass Array 4 (char) : ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 270, 200, 20);

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jLabel10.setText("SuperClass Array 5 (String) : ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 300, 200, 20);

        jTextField2.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(210, 30, 160, 20);

        jTextField3.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(210, 60, 160, 20);

        jTextField4.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(210, 90, 160, 20);

        jTextField5.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(210, 120, 160, 20);

        jTextField6.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jPanel1.add(jTextField6);
        jTextField6.setBounds(210, 150, 160, 20);

        jComboBox1.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(210, 180, 160, 20);

        jComboBox2.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(210, 210, 160, 20);

        jComboBox3.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(210, 240, 160, 20);

        jComboBox4.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(210, 270, 160, 20);

        jComboBox5.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(210, 300, 160, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 20, 390, 340);

        jList1.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(410, 20, 280, 590);

        jButton1.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jButton1.setText("Sort Collection");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 570, 190, 40);

        jButton2.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jButton2.setText("Create Multiple Objects");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 370, 190, 40);

        jButton3.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jButton3.setText("Add Object To Tree");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 570, 190, 40);

        jButton4.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jButton4.setText("Save Collection To File");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(210, 420, 190, 40);

        jButton5.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jButton5.setText("Add Object To LinkedList");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 420, 190, 40);

        jButton6.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jButton6.setText("Add Object To Stack");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(10, 470, 190, 40);

        jButton7.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jButton7.setText("Add Object To Queue");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(10, 520, 190, 40);

        jButton8.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jButton8.setText("Create Random Object");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(10, 370, 190, 40);

        jButton9.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jButton9.setText("Open Collection From File");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(210, 470, 190, 40);

        jButton10.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jButton10.setText("Search Collection");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(210, 520, 190, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        engine.createRandomObjects();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        engine.addRandomObjectToTree();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        engine.saveListToFile();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        engine.sortListBox();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        engine.listboxClick();
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        engine.addRandomObjectToList();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        engine.addRandomObjectToStack();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        engine.addRandomObjectToQueue();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        engine.createRandomObject();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        engine.openListFromFile();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        engine.searchListBox();
    }//GEN-LAST:event_jButton10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
